apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: drupal
    tier: nginx-fpm
    environment: dev
spec:
  selector:
    app: drupal
    tier: nginx-fpm
    environment: dev
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
#    nodePort: 31085
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pv-claim
  labels:
    app: drupal
    tier: nginx-fpm
    environment: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
    tier: nginx-fpm
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
      tier: nginx-fpm
      environment: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: nginx-fpm
        environment: dev
    spec:
      terminationGracePeriodSeconds: 30
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "php-fpm"
      imagePullSecrets:
      - name: regsecret
      containers:
      - image: "dragosdumi/mysite-nginx:latest"
        imagePullPolicy: "Always"
        name: nginx
        ports:
        - containerPort: 80
          name: drupal
        volumeMounts:
        -
          mountPath: /var/www
          name: shared-volume
          readOnly: false
        - name: drupal-persistent-storage
          mountPath: /var/www/docroot/sites/default/files
          subPath: public-files
        - name: drupal-persistent-storage
          mountPath: /var/www/private-files
          subPath: private-files

      - image: "dragosdumi/mysite-app-image:latest"
        name: php-cli
        imagePullPolicy: Always
        env:
        - name: ENVIRONMENT
          value: stage
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-pass
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-pass
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-pass
              key: password
        - name: REDIS_HOST
          value: redis-master
        - name: PUBLIC_FILES
          value: sites/default/files
        - name: PRIVATE_FILES
          value: private-files
        - name: RSYNC_SOURCE
          value: /app
        - name: DRUPAL_ROOT
          value: /var/www/docroot
        - name: PROJECT_ROOT
          value: /var/www
        ports:
        - containerPort: 9000
          name: fastcgi
        volumeMounts:
        -
          mountPath: /var/www
          name: shared-volume
          readOnly: false
        -
          name: drupal-persistent-storage
          mountPath: /var/www/docroot/sites/default/files
          subPath: public-files
        -
          name: drupal-persistent-storage
          mountPath: /var/www/private-files
          subPath: private-files

      - image: "dragosdumi/mysite-php-fpm:latest"
        name: php-fpm
        imagePullPolicy: Always
        env:
        - name: ENVIRONMENT
          value: stage
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-pass
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-pass
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-pass
              key: password
        - name: REDIS_HOST
          value: redis-master
        - name: PUBLIC_FILES
          value: sites/default/files
        - name: PRIVATE_FILES
          value: private-files
        - name: DRUPAL_ROOT
          value: /var/www/docroot
        - name: PROJECT_ROOT
          value: /var/www
        ports:
        - containerPort: 9000
          name: fastcgi
        volumeMounts:
        -
          mountPath: /var/www
          name: shared-volume
          readOnly: false
        -
          name: drupal-persistent-storage
          mountPath: /var/www/docroot/sites/default/files
          subPath: public-files
        -
          name: drupal-persistent-storage
          mountPath: /var/www/private-files
          subPath: private-files

      volumes:
      - name: drupal-persistent-storage
        persistentVolumeClaim:
          claimName: drupal-pv-claim
      # Ephemeral tmpfs (ramdisk) volume for sharing code.
      - name: shared-volume
        emptyDir: {}
