apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-volume-1
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/drupal-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-volume-2
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/drupal-volume-2
