apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: drupal
    tier: db
    environment: dev
spec:
  ports:
    - port: 3306
  selector:
    app: drupal
    tier: db
    environment: dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: drupal
    tier: db
    environment: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: drupal
    tier: db
    environment: dev
spec:
  selector:
    matchLabels:
      app: drupal
      tier: db
      environment: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: db
        environment: dev
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-pass
              key: database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-pass
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-pass
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-mysql-pass
              key: root-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          subPath: mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
