raven.settings:
  type: config_object
  label: 'Raven settings'
  mapping:
    client_key:
      type: string
      label: 'Sentry DSN'
    log_levels:
      type: mapping
      label: 'Log levels'
      mapping:
        1:
          type: integer
          label: 'Emergency'
        2:
          type: integer
          label: 'Alert'
        3:
          type: integer
          label: 'Critical'
        4:
          type: integer
          label: 'Error'
        5:
          type: integer
          label: 'Warning'
        6:
          type: integer
          label: 'Notice'
        7:
          type: integer
          label: 'Info'
        8:
          type: integer
          label: 'Debug'
    stack:
      type: boolean
      label: 'Stacktraces'
    timeout:
      type: float
      label: 'Timeout'
    trace:
      type: boolean
      label: 'Reflection tracing'
    fatal_error_handler:
      type: boolean
      label: 'Fatal error handler'
    fatal_error_handler_memory:
      type: integer
      label: 'Reserved memory'
    javascript_error_handler:
      type: boolean
      label: 'JavaScript error handler'
    public_dsn:
      type: string
      label: 'Sentry public DSN'
