client_key: ''
fatal_error_handler: true
fatal_error_handler_memory: 2560
log_levels:
  1: 1
  2: 2
  3: 3
  4: 4
  5: 0
  6: 0
  7: 0
  8: 0
stack: true
timeout: !!float 2
trace: false
javascript_error_handler: false
public_dsn: ''
_core:
  default_config_hash: EJsMMn516WDvtSeOL9Dx7ulP0PnE5dNVCv6AcXolnKg
