# Schema for the configuration files of the shield module.

shield.settings:
  type: config_object
  label: 'Shield settings'
  mapping:
    user:
      type: string
      label: 'The username'
    pass:
      type: string
      label: 'The password'
    allow_cli:
      type: boolean
      label: 'CLI bypass'
    print:
      type: string
      label: 'The greeting text, [user] and [pass] tokens are usable.'
